# This is a basic workflow to help you get started with Actions

name: WordCount

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_gist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: update
        run: |
          COUNT=$(find . -name '*.md' -exec cat {} \; | wc -m)
          HTTP_STATUS=$(curl -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIST_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o response.json -s -w '%{http_code}' \
            https://api.github.com/gists/feda703c740af0973eed518fbb50c1bb \
            -d '{"files":{"WordCount":{"content":"'"${COUNT}"'"}}}')
          if [ "$HTTP_STATUS" -ne 200 ]; then
            exit $HTTP_STATUS   
          fi
